// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvlyqvohvgugwyhssxjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bHlxdm9odmd1Z3d5aHNzeGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzgwMzYsImV4cCI6MjA3MTgxNDAzNn0.0UiGeaeDqi-KJXutlcPe6c8-twsCI8cS7JnejjbmzxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});